// ─── dates.json schema ──────────────────────────────────────────────────────
// Unified data file consumed by: orbital, timeline ribbon, notifications.
// Generated by scripts/generate/dates.js via Claude API + Craft MCP + Google Calendar.

// ─── Primitives ─────────────────────────────────────────────────────────────

export type EventCategory = "work" | "personal" | "travel" | "social";

export type EventSource = "google" | "craft" | "both";

export type ActionStatus = "todo" | "done";

// ─── Action (sub-task) ──────────────────────────────────────────────────────

export interface DateAction {
  id: string;
  name: string;
  status: ActionStatus;
}

// ─── Single event ───────────────────────────────────────────────────────────

export interface DateEvent {
  /** Stable slug for cross-run identity, e.g. "japan-trip-2026" */
  id: string;

  name: string;

  /** ISO date string YYYY-MM-DD */
  startDate: string;

  /** 1 = single-day, >1 = multi-day span */
  durationDays: number;

  /** 1–10, assigned by the LLM based on context + deadlines */
  importance: number;

  category: EventCategory;

  /** Where this event was derived from */
  source: EventSource;

  /** Weekly standup, recurring 1:1, etc. */
  isRecurring: boolean;

  /** One-sentence summary of what's going on */
  context: string;

  /** Call-to-action nudge. Only present when actions exist. */
  hook?: string;

  /** Sub-tasks. Empty array when none. */
  actions: DateAction[];

  /** People involved. Empty array when none. */
  people: string[];
}

// ─── Root payload ───────────────────────────────────────────────────────────

export interface DatesData {
  /** ISO timestamp of when this file was generated */
  generatedAt: string;

  /** Max lookahead window used during generation */
  windowDays: number;

  events: DateEvent[];
}

// ─── Derived helpers (convenience for consumers) ────────────────────────────

/** Compute days from today to an event's start date */
export function daysUntil(event: DateEvent): number {
  const now = new Date();
  now.setHours(0, 0, 0, 0);
  const start = new Date(event.startDate + "T00:00:00");
  return Math.max(0, Math.round((start.getTime() - now.getTime()) / (1000 * 60 * 60 * 24)));
}

/** True when durationDays > 1 — ribbon renders these as span bars */
export function isMultiDay(event: DateEvent): boolean {
  return event.durationDays > 1;
}

/** Count of incomplete actions */
export function openActionCount(event: DateEvent): number {
  return event.actions.filter((a) => a.status === "todo").length;
}

/** Filter to events starting within the next N days */
export function withinDays(events: DateEvent[], n: number): DateEvent[] {
  return events.filter((e) => daysUntil(e) <= n);
}